name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: code-by-nusrat
          outputs: |
            dist/snake.svg

      - name: Publish snake
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/code-by-nusrat/code-by-nusrat.git repo

          cd repo

          git checkout --orphan snake-output
          git rm -rf . || true

          cp ../dist/snake.svg .

          git add snake.svg
          git commit -m "Update snake animation"
          git push origin snake-output --force
